language: python
python:
  - 2.7

sudo: required
dist: xenial

#install:
#  - pip install -r requirements.txt

script:
  - python -m py_compile norsthstar_provision_new_lsp.py
  - python -m py_compile northstar_get_actives_lsp.py
  - python -m py_compile northstar_get_all_lsp.py

 branches:
  only:
   - master

notifications:
  email:
    recipients:
      - khelil.sator.git@gmail.com
    on_failure: always
  slack: 
    ksator-junos:XAUJP6A29mgYtUtGIJQdPBS7
