language: python
python:
  - 2.7

sudo: required
dist: xenial

install:
  - pip install -r requirements.txt

script:
  - python -m py_compile provision_new_LSP.py
  - python -m py_compile get_active_LSPs.py
  - python -m py_compile get_all_LSPs.py
  - python -m py_compile provision_new_LSPs.py
  - python -m py_compile delete_LSPs.py
  - python -m py_compile put_nodes_in_maintenance.py

branches:
  only:
   - master

notifications:
  email:
    recipients:
      - khelil.sator.git@gmail.com
    on_failure: always
  slack: 
    ksator-junos:XAUJP6A29mgYtUtGIJQdPBS7
